spring:
  application: 
    name: provide-service

server:
  context-path: /
  port: 8012
  
eureka:
  client:
    service-url:
      ##单点配置:
      defaultZone: http://eureka.likegirl.cn/eureka/
      ##高可用配置
      ##defaultZone: http://:8001/eureka/,http://eureka2:8002/eureka/  
  