server:
  context-path: /
  port: 3000
  
eureka:
  client:
    # 是否将自己注册到Eureka服务中，默认为true
    registerWithEureka: true
    service-url:
      ## 单点配置:
#      defaultZone: http://eureka.likegirl.cn/eureka/
      ## 高可用配置
      ## defaultZone: http://:8001/eureka/,http://eureka2:8002/eureka/
      defaultZone: http://user:password123@192.168.11.45:8761///eureka   #设置了账号密码

spring:
  application:
      name: api
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: pro
  aop:
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    # 启用默认的资源处理
    add-mappings: false
  cloud:
    loadbalancer:
      retry:
        enabled: true
  rabbitmq:
      host: 114.67.226.113
      port: 5672
      username: admin
      password: 123456
      virtual-host: /
      #支持发布确认
      publisher-confirms: true
      #支持发布返回
      publisher-returns: true
      listener:
        simple:
        #采用手动应答
          acknowledge-mode: manual
          #当前监听容器数量
          concurrency: 1
          max-concurrency: 1
          #是否支持重试
          retry:
            enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.likegirl.rt.model
  mapper-locations: classpath:cn/likegirl/rt/mapping/*.xml

mapper:
  identity: MYSQL
  # 是否判断字符串类型 !=''
  notEmpty: false
  # 驼峰转下划线小写形式
  style: camelhumpAndLowercase
  # 可以控制是否支持（getter 和 setter）在方法上使用注解，默认false
  enableMethodAnnotation: true
  mappers: cn.likegirl.rt.config.database.BaseMapper

logging:
  level:
#    root: error
    cn.likegirl.rt: debug
    tk.mybatis: trace

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

app:
  message:
    basename: classpath:i18n/messages

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 12000

tms-mgr:
  ribbon:
    ## 只适应ribbon组件 下面这个配置 并未卵~~~
#    ConnectTimeout: 250   # 链接超时时间
#    ReadTimeout: 3000     # 处理超时时间
    # 是否对所有的请求都进行重试
    OkToRetryOnAllOperations: false
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 3
    # 对当前实例的重试次数
    ribbon.MaxAutoRetries: 0

custom:
  rest:
    connect-timeout: 2000
    connection-request-timeout: 2000
    read-timeout: 3000
endpoints:
  shutdown:
    enabled: true
management:
  context-path: /manage
  address: 192.168.11.83
  security:
    enabled: false
security:
  basic:
    enabled: false