server:
  port: 8001
    
eureka: 
  instance:
    hostname: eureka-server
    ##客户端向服务器（注册中心发送心跳的时间间隔）
    lease-renewal-interval-in-seconds: 10   
    ##服务器（注册中心）租期到期的时间, 也就是说服务器在收到最后一次心跳的时间上线
    lease-expiration-duration-in-seconds: 120 
  client:
    service-url:
      ##互相注册到对方--高可用服务发现
      defaultZone: http://118.89.144.30:8001/eureka/,http://193.112.133.164:8001/eureka/
    ## 是否注册自己
    register-with-eureka: true
    ## 是否需要同步其他的Eureka Server节点的数据
    fetch-registry: true